import type { Metadata } from "next";
import {Carter_One, Geist, Geist_Mono} from "next/font/google";
import { Alexandria } from "next/font/google";
import "./globals.css";
import {CartProvider} from "@/Context/CartContext";
const alexandria = Alexandria({
  subsets: ["arabic"], // مهم حتى يدعم العربية
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={alexandria.className}>
      <CartProvider>
          {children}
      </CartProvider>
      </body>
    </html>
  );
}
